INSERT INTO users (username, password, createdAt, updatedAt)
VALUES ('Duc', '1234', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	('Frantz', '1234', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('George', '1234', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);