INSERT INTO users (username, password, createdAt, updatedAt)
VALUES ('1', '1234', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	('2', '1234', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('3', '1234', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);